tunnel:
  enabled: true
  token: "${CLOUDFLARE_TUNNEL_TOKEN_GRAFANA}"
  protocol: "http2"
  noTLSVerify: false
  originServerName: "kubernetes.default.svc.cluster.local"

ingress:
  - hostname: "${GRAFANA_SUBDOMAIN}.${DOMAIN_NAME}"
    service: grafana
    path: "/"
    port: 3000

config:
  http2Origin: true
  disableChunkedEncoding: false
  proxySettings:
    connectTimeout: 30s
    tlsTimeout: 10s
    tcpKeepAlive: 30s
  headers:
    - key: X-Content-Type-Options
      value: nosniff
    - key: X-Frame-Options
      value: DENY
    - key: X-XSS-Protection
      value: "1; mode=block"
    - key: Strict-Transport-Security
      value: "max-age=31536000; includeSubDomains"

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 500Mi