tunnel:
  enabled: true
  token: "${CLOUDFLARE_TUNNEL_TOKEN_WAZUH}"
  protocol: "http2"
  noTLSVerify: false
  originServerName: "kubernetes.default.svc.cluster.local"

ingress:
  - hostname: "${WAZUH_SUBDOMAIN}.${DOMAIN_NAME}"
    service: wazuh-dashboard
    path: "/"
    port: 443

config:
  http2Origin: true
  disableChunkedEncoding: false
  proxySettings:
    connectTimeout: 30s
    tlsTimeout: 10s
    tcpKeepAlive: 30s
  headers:
    - key: X-Content-Type-Options
      value: nosniff
    - key: X-Frame-Options
      value: DENY
    - key: X-XSS-Protection
      value: "1; mode=block"
    - key: Strict-Transport-Security
      value: "max-age=31536000; includeSubDomains"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi