indexer:
  replicaCount: 1
  heap_size: 1g
  storage:
    size: 50Gi
    storageClassName: managed-premium

dashboard:
  replicaCount: 1
  service:
    type: ClusterIP

manager:
  replicaCount: 1
  service:
    type: ClusterIP
  filebeat:
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"